### ISSUE TITLE
Issue with program crashing upon startup

### ISSUE THREAD

**Issue by alden-tennison** [fairdataihub/SODA-for-SPARC#129] opened 2022-07-29 16:42 UTC
**Describe the issue**
I'm having an issue with the program crashing. The program crashes when it tries to connect to the servers, and then doesn't start after that until I restart my computer, where it then crashes again if it tries to connect. It appears that the application in C:\Users\______\AppData\Local\Programs\SODA for SPARC\resources\app\pyflaskdist
is still running after the crash. When I run the program again, there are multiple instances of this application running.

**To Reproduce**
Steps that leads to the issue:

1. Run SODA for the first time.
2. Program runs until connecting to server, then crashes.
3. Run SODA for a second time, crashes immediately.

**Expected behavior**
I expect the program to not crash upon connecting to the server.

**Screenshots**
None

**Operating system used:**
Windows 10

**Additional context**
I have tried restarting my computer, reinstalling SODA in different locations, and running as administrator.

**Comment by bvhpatel** [comment] 2022-07-29 17:15
Sorry about the issue you are having with SODA. It is working properly on our Windows 10 computers so we have not been able to reproduce this issue. Could you please send us the SODA logs file located at C:\Users\your-username\AppData\Roaming\SODA for SPARC\logs and possibly also at C:\Users\your-username\SODA\logs? Perhaps we could learn more from them. You can send us the log file here or via email (I have emailed you as well btw).

**Comment by bvhpatel** [comment] 2022-07-29 18:52
The issue is coming from how SODA is checking for the Pennsieve config file. The issue was addressed for @alden-tennison by configuring their Pennsieve profile directly through the command prompt. To address this in SODA, we need to consider the case where the Pennsieve agent is installed but the Pennsieve config file is not created yet. @aaronm-2112 is working on a fix and will release an update so this issue is not reproduced by other users.

**Comment by aaronm-2112** [comment] 2022-08-01 17:21
This issue has been resolved in the SODA for SPARC 7.0.1 release with commit #131 .

**Closed by aaronm-2112** 2022-08-01 17:21 UTC
Labels: bug
